#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
cd $DIR
MODE=release
if [ $MODE = "release" ]; then
    echo Building release version...
    PATH=$DIR/clang/bin:/usr/lib/llvm-3.9/bin:$PATH
    OPT_G=
    OPT_O=-O3
else
    echo Building debug version...
    #PATH=$DIR/../../llvm/build/bin:$PATH
    PATH=$DIR/clang/bin:/usr/lib/llvm-3.9/bin:$PATH
    OPT_G=-g
    OPT_O=-O0
fi
clang -x c -o $DIR/bangra.h -C -E $DIR/bangra.cpp \
&& clang -c -o $DIR/linenoise.o $DIR/external/linenoise-ng/src/linenoise.cpp -O2 \
    -I $DIR/external/linenoise-ng/include -std=gnu++11 -fno-rtti \
&& clang -c -o $DIR/ConvertUTF.o $DIR/external/linenoise-ng/src/ConvertUTF.cpp -O2 \
    -I $DIR/external/linenoise-ng/include -std=gnu++11 -fno-rtti \
&& clang -c -o $DIR/wcwidth.o $DIR/external/linenoise-ng/src/wcwidth.cpp -O2 \
    -I $DIR/external/linenoise-ng/include -std=gnu++11 -fno-rtti \
&& clang++ \
    -o $DIR/bangra $DIR/bangra.cpp \
    -pedantic \
    $OPT_G -rdynamic \
    -ferror-limit=1 \
    -Wno-vla-extension \
    -DBANGRA_CPP_IMPL -DBANGRA_MAIN_CPP_IMPL \
    -D_GLIBCXX_USE_CXX11_ABI=0 \
    -lpthread -lm -ldl -ltinfo -lz \
    -I$DIR/libffi/include $DIR/libffi/.libs/libffi.a \
    -lclangFrontend -lclangDriver \
    -lclangSerialization -lclangCodeGen -lclangParse -lclangSema \
    -lclangAnalysis \
    -lclangEdit -lclangAST -lclangLex -lclangBasic \
    -Wl,--export-dynamic \
    `llvm-config --cxxflags` \
    `llvm-config --ldflags` \
    -Wl,--whole-archive \
    $DIR/linenoise.o $DIR/ConvertUTF.o $DIR/wcwidth.o \
    `llvm-config --libs engine passes option objcarcopts coverage support` \
    -Wl,--no-whole-archive \
    $OPT_O \
    -fexceptions \
&& $DIR/bangra $DIR/testing/test_all.b
# && gdb --ex r --silent --args $DIR/bangra $DIR/testing/test_bangra.b
