#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
cd $DIR
MODE=release
if [ $MODE = "release" ]; then
    echo Building with clang release version...
    PATH=$DIR/clang/bin:/usr/lib/llvm-3.8/bin:$PATH
else
    echo Building with clang debug version...
    PATH=$DIR/../../llvm/build/bin:$PATH
fi
clang -x c -o $DIR/bangra.h -C -E $DIR/bangra.cpp \
&& clang++ \
    -shared \
    -o $DIR/libbangra.so $DIR/bangra.cpp \
    -pedantic -g \
    -ferror-limit=1 \
    -Wno-vla-extension \
    -DBANGRA_CPP_IMPL \
    -lpthread -lm -ldl -ltinfo -lz \
    -lclangFrontend -lclangDriver \
    -lclangSerialization -lclangCodeGen -lclangParse -lclangSema \
    -lclangAnalysis \
    -lclangEdit -lclangAST -lclangLex -lclangBasic \
    `llvm-config --cxxflags` \
    `llvm-config --ldflags` \
    -Wl,--whole-archive \
    `llvm-config --libs engine` \
    -Wl,--no-whole-archive \
&& clang++ \
    -o $DIR/bangra $DIR/bangra.cpp -DBANGRA_MAIN_CPP_IMPL -O2 -L$DIR \
    -Wl,-rpath '-Wl,$ORIGIN' -lbangra \
&& $DIR/bangra $DIR/bangra.b
# && gdb --ex r --silent --args $DIR/bangra $DIR/bangra.b
